### ISSUE TITLE
The requested qty is not available (truncate inventory_reservation Table)

### ISSUE THREAD

**Issue by steveberrill** [AmpersandHQ/magento2-disable-stock-reservation#41]
Even though i installed this module to block writing to the inventory_reservation table. There were entries added before so they were still causing problems and was not able to order the sku products that still existed in this table

Would be good for the module to truncate this table when the module  is installed/enabled.

**Comment by convenient** [comment]
@kingberrill Great point! 

I wonder whether it would be better to do this as a CLI command so that it could be run asynchronously from the `setup:upgrade` deployment. On databases with massive numbers of products/reservations it could increase the downtime on deployment. Something like `php bin/magento ampersand:disable-stock-reservation:truncate-reservations` or something like that.

I don't have capacity for this right now, but I've added some labels and will also add a note to the README.md to truncate that table after installing

**Comment by maxacarvalho** [comment]
Hello @convenient  

I wonder if you simply mean that the `inventory_reservation` should be truncated by running `truncate table inventory_reservation;` directly in the database or if it's something that should be done from the application?

Thanks.

**Comment by convenient** [comment]
@maxacarvalho Directly in the database, sorry for lack of clarity.

**Comment by maxacarvalho** [comment]
No problem @convenient, thank you very much.

**Comment by convenient** [comment]
@maxacarvalho Also make sure to test everything locally, never do this kind of thing directly on prod without backups and testing first.

**Comment by maxacarvalho** [comment]
Hi @convenient   

Sure, it's being tested in our development environment at the moment. Thank you very much once again.

**Comment by jamacio** [comment]
I implemented the solution on command, I hope I can help you

https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/49

**Comment by jamacio** [comment]
> @kingberrill Great point!
> 
> I wonder whether it would be better to do this as a CLI command so that it could be run asynchronously from the `setup:upgrade` deployment. On databases with massive numbers of products/reservations it could increase the downtime on deployment. Something like `php bin/magento ampersand:disable-stock-reservation:truncate-reservations` or something like that.
> 
> I don't have capacity for this right now, but I've added some labels and will also add a note to the README.md to truncate that table after installing

I implemented the solution on command, I hope I can help you https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/49

**Comment by convenient** [comment]
@gentookid that was never merged i'm afraid, sorry.

Manually truncate the table please

**Comment by gentookid** [comment]
Correct, although I seem to be missing the inventory-reservation table, what I do have is:
inventory_stock_1
inventory_stock_1.website_id             
inventory_stock_1.is_salable
inventory_stock_1.product_id
inventory_stock_1.quantity
inventory_stock_1.sku
inventory_stock_1.stock_id 

Could it be something differs in the schema from versions?

**Comment by convenient** [comment]
The table is `inventory_reservation`

It should be there is you have the inventory tables installed

**Comment by zeeshan2523806** [comment]
@convenient there seems to be an issue when we order all available quantities for a specific item in a single order and then cancel that order from admin. Once we cancel, the stock Quantity is back to normal but the stock status is still the same as Out of Stock which as a result disappears the item from the frontend and does not let users add to the cart.

**Comment by bogdanignat** [comment]
@zeeshan2523806 same issue.
Any ideea, someone, on how to resolve this?

**Comment by RikvdHeijden** [comment]
@zeeshan2523806 @bogdanignat 

This is not an issue with this module, but rather the default behavior of Magento itself. Magento does not register how a product reached it's out of stock status (automatically when the stock falls below the out of stock threshold, or because the stock status attribute was changed) therefore Magento cannot (and does not) assume an increase in available qty means the product itself is back in stock.

If you want this to work you could look at the answer in this stack overflow post: https://magento.stackexchange.com/questions/320979/how-to-automatically-change-the-status-to-in-stock-if-products-are-added-to-the

**Comment by tr33m4n** [comment]
Hello peeps, is this still an issue? Thanks
